import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SigninPage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/aboutus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Aboutus
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/causes" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Causes
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/causessingle" style={{ color: "#87CEFA", textDecoration: "none" }}>
            CausesSingle
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/donationnow" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Donationnow
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/team" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Team
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/volunteer" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Volunteer
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/blogsingle" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BlogSingle
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contactus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ContactUs
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signuppage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SignupPage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminlogin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminLogin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/forgetpassword" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ForgetPassword
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
